import { Evenement } from './Evenement';
import { Customer } from './Customer';

export class Order {
order_id: number;
date_of_order: string;
publication: string;
issue_number: string;
tagline: string;
order_type: string;
new_or_pickup: string;
columns: number;
inches: number;
column_inches: number;
color_type: string;
ad_checking_copy: string;
method_of_delivery: string;
number_of_pictures: number;
number_of_logos: number;
special_placement: string;
proof_date: string;
sale_bills: number;
production_notes: string;
order_notes: string;
csr: string;
sub_total: number;
discount: number;
discount_description: string;
total: number;
automatic_bill: number;
method_of_payment: string;
billing_notes: string;
billing_name: string;
billing_address: string;
billing_city: string;
billing_state: string;
billing_zip: string;
billing_country: string;
billing_phone: string;
billing_fax: string;
billing_email: string;
user: string;
event_date: string;
number_of_ads: number;
average_cost: number;
order_day: number;
order_month: number;
order_year: number;
batched: number;
po_number: string;
no_disc: number;
sales_person: string;
equipment_mart: string;
trn: string;
customer: Customer;
event: Evenement;
}